"""Build the adaptive compressed-reasoning dataset for T1 cold-start.

The script implements the project-specific DA-CoTD-inspired contract:

- prompt difficulty is a deterministic percentile computed only from the
  frozen 2k RLVR prompt pool;
- the 128/256/512 token values are budget anchors, with per-sample budgets
  interpolated and rounded between them;
- short reasoning is kept unchanged; only over-budget reasoning is rewritten
  by the frozen Qwen3 teacher;
- final assistant content is copied byte-for-byte from the accepted teacher
  row and is never generated by the compression model;
- the fixed final answer is rechecked with the official constraint checker;
  reasoning integrity is audited separately with a deterministic stratified
  manual-review queue because answer checks cannot validate intermediate logic.

This is an engineering adaptation, not a full reproduction of DA-CoTD.
"""

from __future__ import annotations

import argparse
import bisect
import copy
import json
import math
import random
import re
import sys
import time
from collections import Counter
from collections.abc import Mapping, Sequence
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Any

import yaml


PROJECT_DIR = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(PROJECT_DIR))

from scripts.sample_thinking_data import (  # noqa: E402
    append_jsonl,
    build_model,
    check_constraints,
    load_existing_ids,
    load_official_ifeval,
    read_jsonl,
    sha256_file,
)


DEFAULT_CONFIG = PROJECT_DIR / "configs" / "rlvr.yaml"
DEFAULT_PROMPT_POOL = PROJECT_DIR / "data" / "rlvr" / "constraint_train_2000.jsonl"
DEFAULT_INPUT = PROJECT_DIR / "data" / "distill" / "t1_thinking_accepted.jsonl"
DEFAULT_OUTPUT = PROJECT_DIR / "data" / "distill" / "t1_thinking_compressed.jsonl"
DEFAULT_REJECTED = PROJECT_DIR / "data" / "distill" / "t1_thinking_compression_rejected.jsonl"
DEFAULT_REVIEW = PROJECT_DIR / "data" / "distill" / "t1_compression_review_60.jsonl"
DEFAULT_AUDIT = PROJECT_DIR / "reports" / "distill" / "da_cotd_compression_audit.json"
DEFAULT_OFFICIAL_REPO = PROJECT_DIR / "third_party" / "Multi-IF"


@dataclass(frozen=True)
class BudgetDecision:
    structural_score: int
    structural_percentile: float
    budget_tokens: int
    budget_band: str


def structural_score(row: dict[str, Any]) -> int:
    """Return prompt-only difficulty from frozen train metadata.

    Teacher success, retries, reasoning length and dev/test results are
    deliberately excluded. They describe trajectory risk, not prompt
    difficulty.
    """

    metadata = row.get("metadata") or {}
    constraints = int(
        metadata.get("constraint_count", len(row.get("instruction_ids", [])))
    )
    turns = int(metadata.get("context_turns", 1))
    categories = len(row.get("constraint_categories") or [])
    return constraints + max(0, turns - 1) + max(0, categories - 1)


def structural_percentile(score: int, sorted_reference_scores: Sequence[int]) -> float:
    """Return the empirical mid-rank percentile in [0, 1]."""

    if not sorted_reference_scores:
        raise ValueError("reference score distribution cannot be empty")
    if len(sorted_reference_scores) == 1:
        return 0.5
    left = bisect.bisect_left(sorted_reference_scores, score)
    right = bisect.bisect_right(sorted_reference_scores, score)
    if left == right:
        insertion_rank = min(max(left, 0), len(sorted_reference_scores) - 1)
        return insertion_rank / (len(sorted_reference_scores) - 1)
    mid_rank = (left + right - 1) / 2
    return min(1.0, max(0.0, mid_rank / (len(sorted_reference_scores) - 1)))


def interpolate_budget(
    percentile: float,
    *,
    easy: int,
    medium: int,
    hard: int,
    round_to: int,
) -> int:
    """Interpolate between the three frozen anchors and round upward."""

    if not (0.0 <= percentile <= 1.0):
        raise ValueError("percentile must be between 0 and 1")
    if not (0 < easy <= medium <= hard):
        raise ValueError("budgets must satisfy 0 < easy <= medium <= hard")
    if round_to < 1:
        raise ValueError("round_to must be positive")

    if percentile <= 0.5:
        raw = easy + (medium - easy) * (percentile / 0.5)
    else:
        raw = medium + (hard - medium) * ((percentile - 0.5) / 0.5)
    rounded = int(math.ceil(raw / round_to) * round_to)
    return min(hard, max(easy, rounded))


def decide_budget(
    row: dict[str, Any],
    reference_scores: Sequence[int],
    anchors: dict[str, int],
    round_to: int,
) -> BudgetDecision:
    score = structural_score(row)
    percentile = structural_percentile(score, reference_scores)
    budget = interpolate_budget(
        percentile,
        easy=int(anchors["easy"]),
        medium=int(anchors["medium"]),
        hard=int(anchors["hard"]),
        round_to=round_to,
    )
    band = "easy" if percentile < 1 / 3 else "medium" if percentile < 2 / 3 else "hard"
    return BudgetDecision(score, percentile, budget, band)


def trajectory_risk(row: dict[str, Any], decision: BudgetDecision) -> dict[str, Any]:
    teacher = row.get("teacher") or {}
    reasoning_tokens = int(teacher.get("reasoning_tokens", 0))
    attempts = int(teacher.get("attempts", 1))
    generated_tokens = int(teacher.get("generated_tokens", 0))
    return {
        "teacher_attempts": attempts,
        "teacher_retried": attempts > 1,
        "original_reasoning_tokens": reasoning_tokens,
        "over_budget_tokens": max(0, reasoning_tokens - decision.budget_tokens),
        "near_teacher_generation_cap": generated_tokens >= 960,
    }


def original_reasoning_answer(row: dict[str, Any]) -> tuple[str, str]:
    teacher = row.get("teacher") or {}
    reasoning = str(teacher.get("reasoning_content") or "")
    answer = str(teacher.get("content") or "")
    if not reasoning.strip() or not answer.strip():
        raise ValueError(f"{row.get('id')}: missing teacher reasoning/content")
    messages = row.get("messages") or []
    if not messages or messages[-1].get("role") != "assistant":
        raise ValueError(f"{row.get('id')}: final assistant message is missing")
    if messages[-1].get("reasoning_content") != teacher.get("reasoning_content"):
        raise ValueError(f"{row.get('id')}: message/teacher reasoning mismatch")
    if messages[-1].get("content") != teacher.get("content"):
        raise ValueError(f"{row.get('id')}: message/teacher answer mismatch")
    return reasoning, answer


def render_task_messages(messages: Sequence[dict[str, Any]]) -> str:
    rendered: list[str] = []
    for message in messages:
        if message.get("role") == "assistant" and "reasoning_content" in message:
            continue
        role = str(message.get("role", "unknown"))
        content = str(message.get("content", ""))
        rendered.append(f"[{role}]\n{content}")
    return "\n\n".join(rendered)


def build_editor_messages(
    row: dict[str, Any],
    reasoning: str,
    budget_tokens: int,
) -> list[dict[str, str]]:
    task = render_task_messages(row["messages"][:-1])
    categories = ", ".join(row.get("constraint_categories") or [])
    instruction_ids = ", ".join(row.get("instruction_ids") or [])
    constraint_parameters = json.dumps(row.get("kwargs") or [], ensure_ascii=False)
    prompt = f"""压缩下面的推理过程。你是推理编辑器，不是答题器。

目标：把“原始推理”改写为不超过 {budget_tokens} 个 tokenizer token 的精炼推理。

必须保留：
1. 任务拆解和关键约束判断；
2. 得出固定最终答案所需的关键步骤；
3. 最终的格式与约束检查。

必须删除：重复自检、无效复述、元话语和与任务无关的解释。
最终答案会由程序从原样本中复制，你不得生成或复述它。只输出压缩后的推理正文，
用“任务判断 -> 关键约束 -> 作答计划 -> 格式检查”的简洁过程表达，不要标题、JSON、代码块或特殊 token。

约束类别：{categories}
约束 ID：{instruction_ids}
约束参数：{constraint_parameters}

任务消息：
{task}

原始推理：
{reasoning}
"""
    return [
        {
            "role": "system",
            "content": "你只压缩已有推理，不重新回答问题。",
        },
        {"role": "user", "content": prompt},
    ]


def clean_editor_output(text: str) -> str:
    cleaned = text.strip()
    for marker in ("<|im_end|>", "<|endoftext|>"):
        while cleaned.endswith(marker):
            cleaned = cleaned[: -len(marker)].rstrip()
    if cleaned.startswith("<think>"):
        cleaned = cleaned[len("<think>") :].strip()
        if "</think>" in cleaned:
            cleaned = cleaned.split("</think>", 1)[0].strip()
    elif "</think>" in cleaned:
        # Qwen chat templates can inject an implicit opening marker. In that
        # form, the useful editor text is before the closing marker.
        cleaned = cleaned.split("</think>", 1)[0].strip()
    if cleaned.startswith("```") and cleaned.endswith("```"):
        cleaned = cleaned[3:-3].strip()
        if cleaned.startswith(("text\n", "markdown\n")):
            cleaned = cleaned.split("\n", 1)[1].strip()
    prefixes = ("压缩后的推理：", "压缩推理：", "推理：")
    for prefix in prefixes:
        if cleaned.startswith(prefix):
            cleaned = cleaned[len(prefix) :].strip()
            break
    # A title constraint in the source prompt can leak a final-answer title
    # into the editor output. Remove only a standalone leading title; mentions
    # of the title requirement inside the reasoning remain untouched.
    cleaned = re.sub(r"^<<[^<>\r\n]+>>\s*(?:\r?\n)?", "", cleaned, count=1).strip()
    return cleaned


def reasoning_copies_fixed_answer(reasoning: str, fixed_answer: str) -> bool:
    """Detect a substantial verbatim answer copy inside edited reasoning."""

    normalized_reasoning = "".join(reasoning.split())
    normalized_answer = "".join(fixed_answer.split())
    return len(normalized_answer) >= 32 and normalized_answer in normalized_reasoning


def generate_editor_output(
    tokenizer,
    model,
    messages: list[dict[str, str]],
    *,
    max_new_tokens: int,
    seed: int,
    do_sample: bool,
    temperature: float,
    top_p: float,
) -> tuple[str, int, bool]:
    import torch

    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)
    encoded = tokenizer.apply_chat_template(
        messages,
        tokenize=True,
        add_generation_prompt=True,
        enable_thinking=False,
        return_tensors="pt",
    )
    model_inputs = dict(encoded) if isinstance(encoded, Mapping) else {"input_ids": encoded}
    if "attention_mask" not in model_inputs:
        model_inputs["attention_mask"] = torch.ones_like(model_inputs["input_ids"])
    input_device = model.get_input_embeddings().weight.device
    model_inputs = {name: value.to(input_device) for name, value in model_inputs.items()}
    generation_kwargs: dict[str, Any] = {
        "max_new_tokens": max_new_tokens,
        "do_sample": do_sample,
        "pad_token_id": tokenizer.eos_token_id,
    }
    if do_sample:
        generation_kwargs.update(temperature=temperature, top_p=top_p)
    with torch.inference_mode():
        output_ids = model.generate(**model_inputs, **generation_kwargs)
    new_ids = output_ids[0, model_inputs["input_ids"].shape[1] :]
    decoded = tokenizer.decode(new_ids, skip_special_tokens=False)
    ended_with_eos = bool(len(new_ids) and int(new_ids[-1]) == tokenizer.eos_token_id)
    return clean_editor_output(decoded), len(new_ids), ended_with_eos


def compressed_row(
    row: dict[str, Any],
    reasoning: str,
    answer: str,
    decision: BudgetDecision,
    *,
    original_tokens: int,
    compressed_tokens: int,
    method: str,
    editor_attempts: int,
    editor_model: str,
    strict_results: Sequence[bool],
) -> dict[str, Any]:
    result = copy.deepcopy(row)
    result["messages"][-1]["reasoning_content"] = reasoning
    result["messages"][-1]["content"] = answer
    result["compression"] = {
        "schema_version": "t1_reasoning_compression/v1",
        "method": method,
        "claim_boundary": "DA-CoTD-inspired project-specific compression",
        "editor_model": editor_model if method == "teacher_rewrite" else None,
        "structural_score": decision.structural_score,
        "structural_percentile": round(decision.structural_percentile, 8),
        "budget_band": decision.budget_band,
        "budget_tokens": decision.budget_tokens,
        "original_reasoning_tokens": original_tokens,
        "compressed_reasoning_tokens": compressed_tokens,
        "compression_ratio": compressed_tokens / original_tokens if original_tokens else None,
        "editor_attempts": editor_attempts,
        "answer_unchanged": answer == row["teacher"]["content"],
        "strict_results": list(strict_results),
        "trajectory_risk": trajectory_risk(row, decision),
    }
    return result


def plan_summary(
    rows: Sequence[dict[str, Any]],
    reference_scores: Sequence[int],
    anchors: dict[str, int],
    round_to: int,
) -> dict[str, Any]:
    methods: Counter[str] = Counter()
    bands: Counter[str] = Counter()
    budgets: Counter[int] = Counter()
    over_by_band: Counter[str] = Counter()
    rewrite_example_ids: list[str] = []
    for row in rows:
        decision = decide_budget(row, reference_scores, anchors, round_to)
        original_tokens = int((row.get("teacher") or {}).get("reasoning_tokens", 0))
        method = "keep" if original_tokens <= decision.budget_tokens else "teacher_rewrite"
        methods[method] += 1
        bands[decision.budget_band] += 1
        budgets[decision.budget_tokens] += 1
        if method == "teacher_rewrite":
            over_by_band[decision.budget_band] += 1
            if len(rewrite_example_ids) < 5:
                rewrite_example_ids.append(str(row.get("id", "")))
    return {
        "rows": len(rows),
        "planned_methods": dict(methods),
        "budget_bands": dict(bands),
        "over_budget_by_band": dict(over_by_band),
        "budget_distribution": {str(k): v for k, v in sorted(budgets.items())},
        "rewrite_example_ids": rewrite_example_ids,
    }


def build_review_queue(
    compressed_rows: Sequence[dict[str, Any]],
    *,
    per_stratum: int,
    seed: int = 42,
) -> list[dict[str, Any]]:
    """Select a deterministic reasoning-integrity review across all strata."""

    if per_stratum < 1:
        raise ValueError("per_stratum must be positive")
    strata: dict[tuple[str, str], list[dict[str, Any]]] = {}
    for row in compressed_rows:
        compression = row.get("compression") or {}
        key = (
            str(compression.get("budget_band", "unknown")),
            str(compression.get("method", "unknown")),
        )
        strata.setdefault(key, []).append(row)

    selected: list[dict[str, Any]] = []
    for stratum_index, key in enumerate(sorted(strata)):
        candidates = sorted(strata[key], key=lambda item: str(item.get("id", "")))
        random.Random(seed + stratum_index).shuffle(candidates)
        for row in candidates[:per_stratum]:
            compression = row["compression"]
            selected.append(
                {
                    "id": row["id"],
                    "stratum": {
                        "budget_band": key[0],
                        "method": key[1],
                    },
                    "budget_tokens": compression["budget_tokens"],
                    "original_reasoning_tokens": compression["original_reasoning_tokens"],
                    "compressed_reasoning_tokens": compression["compressed_reasoning_tokens"],
                    "original_reasoning": row["teacher"]["reasoning_content"],
                    "compressed_reasoning": row["messages"][-1]["reasoning_content"],
                    "fixed_answer": row["teacher"]["content"],
                    "instruction_ids": row.get("instruction_ids", []),
                    "kwargs": row.get("kwargs", []),
                    "review": {
                        "status": "pending",
                        "constraint_reasoning_preserved": None,
                        "causal_order_preserved": None,
                        "no_material_hallucination": None,
                        "decision": None,
                        "notes": "",
                    },
                }
            )
    return sorted(selected, key=lambda item: item["id"])


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--config", type=Path, default=DEFAULT_CONFIG)
    parser.add_argument("--prompt-pool", type=Path, default=DEFAULT_PROMPT_POOL)
    parser.add_argument("--input", type=Path, default=DEFAULT_INPUT)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--rejected-output", type=Path, default=DEFAULT_REJECTED)
    parser.add_argument("--review-output", type=Path, default=DEFAULT_REVIEW)
    parser.add_argument("--audit", type=Path, default=DEFAULT_AUDIT)
    parser.add_argument("--official-repo", type=Path, default=DEFAULT_OFFICIAL_REPO)
    parser.add_argument("--teacher", default="Qwen/Qwen3-4B")
    parser.add_argument("--revision", default="main")
    parser.add_argument("--limit", type=int)
    parser.add_argument(
        "--id",
        action="append",
        dest="row_ids",
        help="Process only this accepted row id; repeat for multiple rows.",
    )
    parser.add_argument("--resume", action="store_true")
    parser.add_argument("--plan-only", action="store_true")
    args = parser.parse_args()

    for path in (args.config, args.prompt_pool, args.input):
        if not path.exists():
            raise FileNotFoundError(path)
    if args.limit is not None and args.limit < 1:
        parser.error("--limit must be positive")
    for path in (args.output, args.rejected_output):
        if path.exists() and not args.resume and not args.plan_only:
            raise FileExistsError(f"Refusing to overwrite {path}; use --resume")

    config = yaml.safe_load(args.config.read_text(encoding="utf-8"))
    t1_config = config["t1"]
    compression_config = t1_config["compression"]
    anchors = {key: int(value) for key, value in t1_config["reasoning_token_budgets"].items()}
    round_to = int(compression_config["budget_round_to_tokens"])
    max_retries = int(compression_config["editor_max_retries"])
    slack = int(compression_config["editor_max_new_token_slack"])
    retry_temperature = float(compression_config["retry_temperature"])
    retry_top_p = float(compression_config["retry_top_p"])
    review_per_stratum = int(compression_config["manual_review_per_stratum"])

    prompt_pool = read_jsonl(args.prompt_pool)
    if len({row.get("id") for row in prompt_pool}) != len(prompt_pool):
        raise ValueError("prompt pool ids must be unique")
    reference_scores = sorted(structural_score(row) for row in prompt_pool)
    rows = read_jsonl(args.input)
    if args.row_ids:
        requested_ids = set(args.row_ids)
        available_ids = {str(row.get("id", "")) for row in rows}
        missing_ids = requested_ids - available_ids
        if missing_ids:
            raise ValueError(f"Requested ids not found: {sorted(missing_ids)}")
        rows = [row for row in rows if str(row.get("id", "")) in requested_ids]
    if args.limit is not None:
        rows = rows[: args.limit]
    if not rows:
        raise ValueError("No accepted teacher rows")
    if len({row.get("id") for row in rows}) != len(rows):
        raise ValueError("accepted input ids must be unique")

    planned = plan_summary(rows, reference_scores, anchors, round_to)
    if args.plan_only:
        print(json.dumps(planned, ensure_ascii=False, indent=2))
        return

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.rejected_output.parent.mkdir(parents=True, exist_ok=True)
    args.review_output.parent.mkdir(parents=True, exist_ok=True)
    args.audit.parent.mkdir(parents=True, exist_ok=True)
    completed = load_existing_ids(args.output) | load_existing_ids(args.rejected_output)
    initial_completed = {row["id"] for row in rows if row["id"] in completed}

    ifeval = load_official_ifeval(args.official_repo)
    tokenizer = model = compute_dtype = None
    kept_new = rewritten_new = rejected_new = editor_attempts_total = 0
    original_token_total = compressed_token_total = 0
    rejection_reasons: Counter[str] = Counter()
    started = time.perf_counter()

    with args.output.open("a", encoding="utf-8") as output_file, args.rejected_output.open(
        "a", encoding="utf-8"
    ) as rejected_file:
        for index, row in enumerate(rows, start=1):
            row_id = str(row.get("id", ""))
            if row_id in completed:
                print(f"[{index}/{len(rows)}] {row_id} skipped")
                continue

            try:
                original_reasoning, original_answer = original_reasoning_answer(row)
                decision = decide_budget(row, reference_scores, anchors, round_to)
                strict_results, checker_error = check_constraints(
                    ifeval, original_answer, row["instruction_ids"], row["kwargs"]
                )
                if checker_error is not None:
                    raise RuntimeError(f"official_checker_error: {checker_error}")
                if not all(strict_results):
                    raise RuntimeError("accepted_input_failed_official_checker")

                stored_tokens = int(row["teacher"].get("reasoning_tokens", 0))
                if stored_tokens <= decision.budget_tokens:
                    final_reasoning = original_reasoning
                    original_tokens = compressed_tokens = stored_tokens
                    method = "keep"
                    attempts_used = 0
                else:
                    if model is None:
                        tokenizer, model, compute_dtype = build_model(args.teacher, args.revision, False)
                    original_tokens = len(
                        tokenizer.encode(original_reasoning, add_special_tokens=False)
                    )
                    if original_tokens <= decision.budget_tokens:
                        final_reasoning = original_reasoning
                        compressed_tokens = original_tokens
                        method = "keep"
                        attempts_used = 0
                    else:
                        editor_messages = build_editor_messages(
                            row,
                            original_reasoning,
                            decision.budget_tokens,
                        )
                        final_reasoning = ""
                        compressed_tokens = 0
                        attempts_used = 0
                        last_failure = "empty_editor_output"
                        for attempt in range(max_retries + 1):
                            attempts_used += 1
                            editor_attempts_total += 1
                            candidate, _, ended_with_eos = generate_editor_output(
                                tokenizer,
                                model,
                                editor_messages,
                                max_new_tokens=decision.budget_tokens + slack,
                                seed=420000 + index * 100 + attempt,
                                do_sample=attempt > 0,
                                temperature=retry_temperature,
                                top_p=retry_top_p,
                            )
                            if not candidate:
                                last_failure = "empty_editor_output"
                                continue
                            candidate_tokens = len(
                                tokenizer.encode(candidate, add_special_tokens=False)
                            )
                            if not ended_with_eos:
                                last_failure = "editor_max_new_tokens_reached"
                                continue
                            if candidate_tokens > decision.budget_tokens:
                                last_failure = "compressed_reasoning_over_budget"
                                continue
                            if reasoning_copies_fixed_answer(candidate, original_answer):
                                last_failure = "compressed_reasoning_copies_fixed_answer"
                                continue
                            final_reasoning = candidate
                            compressed_tokens = candidate_tokens
                            break
                        if not final_reasoning:
                            raise RuntimeError(last_failure)
                        method = "teacher_rewrite"

                result = compressed_row(
                    row,
                    final_reasoning,
                    original_answer,
                    decision,
                    original_tokens=original_tokens,
                    compressed_tokens=compressed_tokens,
                    method=method,
                    editor_attempts=attempts_used,
                    editor_model=args.teacher,
                    strict_results=strict_results,
                )
                append_jsonl(output_file, result)
                completed.add(row_id)
                original_token_total += original_tokens
                compressed_token_total += compressed_tokens
                if method == "keep":
                    kept_new += 1
                else:
                    rewritten_new += 1
                print(
                    f"[{index}/{len(rows)}] {row_id} {method}: "
                    f"{original_tokens}->{compressed_tokens}/{decision.budget_tokens}"
                )
            except Exception as error:
                reason = str(error)
                rejection_reasons[reason] += 1
                append_jsonl(
                    rejected_file,
                    {
                        "id": row_id,
                        "reason": reason,
                        "instruction_ids": row.get("instruction_ids", []),
                        "metadata": row.get("metadata", {}),
                    },
                )
                completed.add(row_id)
                rejected_new += 1
                print(f"[{index}/{len(rows)}] {row_id} compression rejected: {reason}")

    total_output_ids = load_existing_ids(args.output)
    total_rejected_ids = load_existing_ids(args.rejected_output)
    overlap = total_output_ids & total_rejected_ids
    if overlap:
        raise RuntimeError(f"compressed/rejected overlap: {sorted(overlap)[:5]}")
    expected_ids = {row["id"] for row in rows}
    completed_expected = (total_output_ids | total_rejected_ids) & expected_ids
    status = "completed" if completed_expected == expected_ids else "partial"
    compressed_rows = [
        row for row in read_jsonl(args.output) if row.get("id") in expected_ids
    ]
    review_queue = build_review_queue(
        compressed_rows,
        per_stratum=review_per_stratum,
    )
    with args.review_output.open("w", encoding="utf-8") as review_file:
        for review_row in review_queue:
            append_jsonl(review_file, review_row)
    audit = {
        "schema_version": "t1_reasoning_compression_audit/v1",
        "status": status,
        "method": t1_config["method"],
        "claim_boundary": t1_config["claim_boundary"],
        "teacher": args.teacher,
        "revision": args.revision,
        "input": str(args.input.resolve()),
        "input_sha256": sha256_file(args.input),
        "prompt_pool": str(args.prompt_pool.resolve()),
        "prompt_pool_sha256": sha256_file(args.prompt_pool),
        "requested_rows": len(rows),
        "completed_before": len(initial_completed),
        "kept_new": kept_new,
        "rewritten_new": rewritten_new,
        "rejected_new": rejected_new,
        "editor_attempts_new": editor_attempts_total,
        "compressed_rows_total": len(total_output_ids & expected_ids),
        "rejected_rows_total": len(total_rejected_ids & expected_ids),
        "original_reasoning_tokens_new": original_token_total,
        "compressed_reasoning_tokens_new": compressed_token_total,
        "compression_ratio_new": (
            compressed_token_total / original_token_total if original_token_total else None
        ),
        "rejection_reasons_new": dict(rejection_reasons),
        "reasoning_integrity_review": {
            "status": "pending_manual_review",
            "rows": len(review_queue),
            "per_stratum": review_per_stratum,
            "note": "The official checker validates only the fixed final answer.",
        },
        "budget_contract": {
            "anchors": anchors,
            "round_to_tokens": round_to,
            "strategy": compression_config["budget_strategy"],
            "percentile_reference": compression_config["percentile_reference"],
        },
        "planned": planned,
        "generation_seconds_new": time.perf_counter() - started,
        "compute_dtype": (
            str(compute_dtype).replace("torch.", "") if compute_dtype is not None else None
        ),
        "outputs": {
            "compressed": str(args.output.resolve()),
            "rejected": str(args.rejected_output.resolve()),
            "manual_review": str(args.review_output.resolve()),
        },
    }
    args.audit.write_text(json.dumps(audit, ensure_ascii=False, indent=2), encoding="utf-8")
    print(json.dumps(audit, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
